baseurl = "https://kangwoosukeq.github.io"
title = "Home"
theme = "hugo-coder"
languagecode = "ko"
defaultcontentlanguage = "ko"

[params]
author = "Wooseok Kang"
info = "Security Hacker"
avatarurl = "images/kirby.png"
favicon_16 = "images/logos/kirby_favicon.ico"

hideFooter = true
enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"


# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/kangwoosukeq"
[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 3
url = "mailto:kangwoosuk1@gmail.com"

# Menu links
[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
